theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "Frank's bytes"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
  header = "What I'm thinking"
	showglobe = false
	email = "frankkair@gmail.com"
	profilepic = "img/profile.jpg"
	title = "Frank Magagnin Kair"
	subtitle = "Bytes"

	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/FrankKair"

	[[params.socialbuttons]]
	faicon = "linkedin"
  url = "https://www.linkedin.com/in/frank-kair/"

	[[params.navlinks]]
	name = "About"
	url = "about/"

	[[params.navlinks]]
	name = "Blog"
	url = "post/"
