FLAGS: dict[str, str] = {
    "Argentina": "🇦🇷 Argentina",
    "Armenia": "🇦🇲 Armenia",
    "Australia": "🇦🇺 Australia",
    "Austria": "🇦🇹 Austria",
    "Belgium": "🇧🇪 Belgium",
    "Belarus": "🇧🇾 Belarus",
    "Brazil": "🇧🇷 Brazil",
    "Canada": "🇨🇦 Canada",
    "Chile": "🇨🇱 Chile",
    "China": "🇨🇳 China",
    "Croatia": "🇭🇷 Croatia",
    "Cuba": "🇨🇺 Cuba",
    "Czechia": "🇨🇿 Czechia",
    "Denmark": "🇩🇰 Denmark",
    "Estonia": "🇪🇪 Estonia",
    "Ethiopia": "🇪🇹 Ethiopia",
    "Finland": "🇫🇮 Finland",
    "France": "🇫🇷 France",
    "Germany": "🇩🇪 Germany",
    "Greece": "🇬🇷 Greece",
    "Hungary": "🇭🇺 Hungary",
    "Iceland": "🇮🇸 Iceland",
    "India": "🇮🇳 India",
    "Ireland": "🇮🇪 Ireland",
    "Israel": "🇮🇱 Israel",
    "Italy": "🇮🇹 Italy",
    "Jamaica": "🇯🇲 Jamaica",
    "Japan": "🇯🇵 Japan",
    "Lithuania": "🇱🇹 Lithuania",
    "Mali": "🇲🇱 Mali",
    "Mexico": "🇲🇽 Mexico",
    "Morocco": "🇲🇦 Morocco",
    "Netherlands": "🇳🇱 Netherlands",
    "New Zealand": "🇳🇿 New Zealand",
    "Nigeria": "🇳🇬 Nigeria",
    "Norway": "🇳🇴 Norway",
    "Pakistan": "🇵🇰 Pakistan",
    "Papua New Guinea": "🇵🇬 Papua New Guinea",
    "Poland": "🇵🇱 Poland",
    "Portugal": "🇵🇹 Portugal",
    "Russia": "🇷🇺 Russia",
    "Singapore": "🇸🇬 Singapore",
    "South Africa": "🇿🇦 South Africa",
    "South Korea": "🇰🇷 South Korea",
    "Spain": "🇪🇸 Spain",
    "Sweden": "🇸🇪 Sweden",
    "Switzerland": "🇨🇭 Switzerland",
    "Taiwan": "🇹🇼 Taiwan",
    "Türkiye": "🇹🇷 Türkiye",
    "Ukraine": "🇺🇦 Ukraine",
    "UK": "🇬🇧 UK",
    "USA": "🇺🇸 USA",
    "Zambia": "🇿🇲 Zambia",
    "Zimbabwe": "🇿🇼 Zimbabwe",
}
