baseURL = 'https://frankkair.github.io/'
languageCode = 'en-us'
title = 'Frank'
theme = 'cactus'

[params]
colortheme = "dark"
mainSectionTitle = "--"
mainSections = "posts"
showAllPostsOnHomePage = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
