[[publication]]
title = "Books"
csv = "csv/books.csv"
group_by = "date"
stats = ["country"]

[[publication]]
title = "Music"
csv = "csv/music.csv"
group_by = "review"
stats = ["country", "decade:year"]

[[publication]]
title = "Books to read"
csv = "csv/books-to-read.csv"
stats = ["country"]

[[publication]]
title = "Cinema Club"
csv = "csv/cinema-club.csv"
group_by = "watched"
stats = ["country"]

[[publication]]
title = "Movies"
csv = "csv/movies.csv"
group_by = "watched"
stats = ["country"]
