"""Generate collection pages and data without touching authored content."""

import csv
import json
import re
import tomllib
from collections import Counter
from pathlib import Path

from countries import FLAGS

ROOT = Path(__file__).resolve().parents[1]
MARKER = (
    "Generated by generate-markdowns.py; edit the CSV or publications.toml."
)


def load_config(path=ROOT / "publications.toml"):
    with open(path, "rb") as source:
        return tomllib.load(source)


def add_flags(value):
    """Flag known countries; preserve existing flags and historical labels."""
    countries = []
    for country in value.split("/"):
        country = country.strip()
        if country in FLAGS:
            flag = "".join(chr(127397 + ord(c)) for c in FLAGS[country].upper())
            country = f"{flag} {country}"
        if country:
            countries.append(country)
    return " / ".join(countries)


def read_csv(path):
    with open(path, encoding="utf-8", newline="") as source:
        reader = csv.reader(source)
        headers = next(reader)
        if not all(headers) or len(set(headers)) != len(headers):
            raise ValueError(f"{path}: headers must be nonempty and unique")
        rows = []
        for row in reader:
            if not row or not any(row):
                continue
            if len(row) != len(headers):
                raise ValueError(
                    f"{path}:{reader.line_num}: expected {len(headers)} "
                    f"fields, got {len(row)}"
                )
            rows.append(row)
    return headers, rows


def extract_year_from_date(value):
    # Accept partial dates (-/07/2022) and bare years without inventing a day.
    match = re.search(r"(?:^|/)(\d{4})$", value.strip())
    return match[1] if match else None


def compute_stats(headers, rows, configs):
    statistics = []
    for config in configs:
        kind, _, column = config.partition(":")
        column = column or kind
        if column not in headers:
            raise ValueError(f"Unknown statistics column: {column}")
        index = headers.index(column)
        counts = Counter()
        for row in rows:
            if kind == "country":
                counts.update(
                    value.strip()
                    for value in row[index].split("/")
                    if value.strip()
                )
            elif kind == "decade":
                try:
                    counts[f"{int(row[index]) // 10 * 10}s"] += 1
                except ValueError:
                    pass
            else:
                raise ValueError(f"Unknown statistic: {kind}")
        statistics.append(
            {"label": kind.title(), "items": counts.most_common()}
        )
    return statistics


def build_collection(publication, root=ROOT):
    headers, source_rows = read_csv(root / publication["csv"])
    rows = [row.copy() for row in source_rows]
    if "country" in headers:
        index = headers.index("country")
        for row in rows:
            row[index] = add_flags(row[index])

    group_by = publication.get("group_by")
    groups = {}
    if group_by:
        index = headers.index(group_by)
        for row in rows:
            year = extract_year_from_date(row[index]) or "Undated"
            groups.setdefault(year, []).append(row)
        # Newest years first, preserving the curated CSV order within each year.
        years = sorted(
            (year for year in groups if year != "Undated"), reverse=True
        )
        if "Undated" in groups:
            years.append("Undated")
    else:
        groups = {"All entries": rows}
        years = list(groups)

    labels = publication.get("labels", {})
    return {
        "source": publication["csv"],
        "headers": headers,
        "labels": [
            labels.get(header, header.replace("_", " ").title())
            for header in headers
        ],
        "rows": rows,
        "count": len(rows),
        "groups": [{"label": year, "rows": groups[year]} for year in years],
        "grouped": bool(group_by),
        "stats": compute_stats(headers, rows, publication.get("stats", [])),
    }


def generate(root=ROOT):
    publications = load_config(root / "publications.toml").get(
        "publication", []
    )
    outputs = {}
    slugs = set()
    total = 0
    for weight, publication in enumerate(publications, 1):
        if not publication.get("published", True):
            continue
        slug = publication["slug"]
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug) or slug in slugs:
            raise ValueError(f"Invalid or duplicate collection slug: {slug}")
        slugs.add(slug)
        data = build_collection(publication, root)
        total += data["count"]
        front_matter = {
            "title": publication["title"],
            "description": publication.get("description", ""),
            "type": "collections",
            "collection": slug,
            "icon": publication.get("icon", "book"),
            "count": data["count"],
            "weight": weight,
            "aliases": publication.get("aliases", []),
            "outputs": ["HTML"],
            "generated_by": MARKER,
        }
        # JSON front matter avoids quoting and Unicode ambiguities.
        outputs[root / "content/collections" / f"{slug}.md"] = (
            json.dumps(front_matter, ensure_ascii=False, indent=2) + "\n"
        )
        outputs[root / "data/collections" / f"{slug}.json"] = (
            json.dumps(data, ensure_ascii=False, indent=2) + "\n"
        )

    # Validate every source before writing. Guard authored files placed at
    # one of the generated Markdown paths.
    for path in outputs:
        if (
            path.suffix == ".md"
            and path.exists()
            and MARKER not in path.read_text(encoding="utf-8")
        ):
            raise ValueError(f"Refusing to overwrite authored content: {path}")
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")

    # Remove only marked, obsolete generated pages (e.g. published = false).
    for path in (root / "content/collections").glob("*.md"):
        if path not in outputs and MARKER in path.read_text(encoding="utf-8"):
            path.unlink()
            data_path = root / "data/collections" / f"{path.stem}.json"
            data_path.unlink(missing_ok=True)
    print(f"Generated {len(slugs)} collections ({total} entries).")


if __name__ == "__main__":
    generate()
